
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;

	private global::Gtk.DrawingArea daCanvas;

	private global::Gtk.Entry eInput;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button button6;

	private global::Gtk.Button button8;

	private global::Gtk.Label label3;

	private global::Gtk.SpinButton sbStep;

	private global::Gtk.Label label1;

	private global::Gtk.SpinButton sbAng;

	private global::Gtk.Button button1;

	private global::Gtk.Frame frame4;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.Label lOutput;

	private global::Gtk.Label GtkLabel3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Draw tool");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.daCanvas = new global::Gtk.DrawingArea();
		this.daCanvas.Name = "daCanvas";
		this.vbox2.Add(this.daCanvas);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.daCanvas]));
		w1.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.eInput = new global::Gtk.Entry();
		this.eInput.CanFocus = true;
		this.eInput.Name = "eInput";
		this.eInput.Text = global::Mono.Unix.Catalog.GetString("ffhhhffvvfff");
		this.eInput.IsEditable = true;
		this.eInput.InvisibleChar = '●';
		this.vbox2.Add(this.eInput);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.eInput]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Step");
		this.hbox1.Add(this.button6);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button6]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.hbox1.Add(this.button8);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button8]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Step length");
		this.hbox1.Add(this.label3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.sbStep = new global::Gtk.SpinButton(1D, 1000D, 1D);
		this.sbStep.CanFocus = true;
		this.sbStep.Name = "sbStep";
		this.sbStep.Adjustment.PageIncrement = 10D;
		this.sbStep.ClimbRate = 1D;
		this.sbStep.Numeric = true;
		this.sbStep.Value = 10D;
		this.hbox1.Add(this.sbStep);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.sbStep]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Angle step");
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w7.Position = 4;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.sbAng = new global::Gtk.SpinButton(1D, 179D, 1D);
		this.sbAng.CanFocus = true;
		this.sbAng.Name = "sbAng";
		this.sbAng.Adjustment.PageIncrement = 10D;
		this.sbAng.ClimbRate = 1D;
		this.sbAng.Numeric = true;
		this.sbAng.Value = 10D;
		this.hbox1.Add(this.sbAng);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.sbAng]));
		w8.Position = 5;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Fast Forward");
		this.hbox1.Add(this.button1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
		w9.PackType = ((global::Gtk.PackType)(1));
		w9.Position = 6;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.HeightRequest = 50;
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.lOutput = new global::Gtk.Label();
		this.lOutput.HeightRequest = 50;
		this.lOutput.Name = "lOutput";
		this.lOutput.LabelProp = global::Mono.Unix.Catalog.GetString("Ready");
		this.GtkAlignment2.Add(this.lOutput);
		this.frame4.Add(this.GtkAlignment2);
		this.GtkLabel3 = new global::Gtk.Label();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Result</b>");
		this.GtkLabel3.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel3;
		this.vbox2.Add(this.frame4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame4]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 642;
		this.DefaultHeight = 538;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button6.Clicked += new global::System.EventHandler(this.StepClicked);
		this.button8.Clicked += new global::System.EventHandler(this.StopClicked);
		this.button1.Clicked += new global::System.EventHandler(this.FastForwardClicked);
	}
}
